spring:
  security:
    oauth2.client:
      registration:
        github:
          client-id: Ov23likkkIMIFQYOM514
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
custom:
  client:
    domain: http://localhost
    port: 5173
