name: 배포

on:
  push:
    branches: [main, deploy/33-BE_cd]
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          password: ${{ secrets.REMOTE_SHH_PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            echo $BRANCH_NAME

            cd workspaces/1day1baek/back
            git checkout -B $BRANCH_NAME
            git pull origin $BRANCH_NAME

            ./stop_server.sh
            ./run_sandbox.sh